-- naehrbert / NutriWise — single-file Supabase setup.
--
-- Run this ONCE, in full, in a fresh Supabase project's SQL editor
-- (Dashboard -> SQL Editor -> New query -> paste -> Run). It creates the
-- entire schema this app needs, from scratch, in the final shape the
-- deployed project is actually running today.
--
-- This file is a consolidation of what used to be 20 incremental,
-- chronologically-numbered migration files (0001..0019 -- two shared the
-- "0010" prefix). That history -- and the reasoning behind each
-- individual change -- is preserved in git history (`git log -- supabase/`)
-- if you ever want to dig into it, but this single file is the one to
-- actually run for a fresh project. If you change the schema again later,
-- just fold the change directly into this file so it stays a true
-- "one-shot" setup rather than reintroducing a migrations/ directory.
--
-- Auth note: `profiles.auth_user_id` references `auth.users`, Supabase's
-- own built-in auth schema -- nothing to enable, every Supabase project
-- has it. Email/password + Google sign-in themselves are configured in
-- Dashboard -> Authentication (see README.md for exactly what to flip on).
--
-- Security note: every table below ends up with row-level security
-- enabled and NO policies. That is deliberate, not a gap to fill in later
-- -- this app never lets the browser talk to Supabase for data (only for
-- auth); all data access goes through the FastAPI backend, which connects
-- with the service_role key and so bypasses RLS entirely. RLS-enabled +
-- zero policies just means "deny the public anon/authenticated Data API
-- on this table", closing the auto-exposed REST endpoint Supabase turns on
-- for every table by default. If you ever let the browser query Supabase
-- directly for app data, add real policies first.

-- ── profiles ────────────────────────────────────────────────────────────
-- One row per signed-up user (originally single-user with id pinned to 1;
-- multi-user since migration 0007, hence the identity column instead of a
-- fixed default). auth_user_id links a row to its Supabase Auth account
-- (migration 0016) -- nullable because it's populated when an account
-- claims/creates its profile, not at row-creation time in every code path.
create table profiles (
    id                       smallint generated by default as identity primary key,
    sex                      text not null check (sex in ('female', 'male', 'prefer_not_to_say')),
    date_of_birth            date not null,
    height_cm                numeric not null check (height_cm between 100 and 250),
    weight_kg                numeric not null check (weight_kg between 30 and 300),
    exercise_frequency       text not null check (exercise_frequency in ('none', 'one_two', 'three_four', 'five_six', 'daily_athlete')),
    daily_movement           text not null check (daily_movement in ('mostly_sitting', 'mixed', 'mostly_standing', 'physical_labor')),
    goal                     text not null check (goal in ('lose_weight_gradually', 'maintain', 'build_muscle')),
    name                     text,
    dietary_style            text check (dietary_style in ('omnivore', 'pescatarian', 'vegetarian', 'vegan')),
    allergies                text[] not null default '{}',
    dislikes                 text[] not null default '{}',
    recipe_prefs_completed_at timestamptz,
    household_size           smallint check (household_size between 1 and 20),
    consumption_share_pct    numeric check (consumption_share_pct between 1 and 100),
    life_stage               text check (life_stage in ('none', 'pregnant_t1', 'pregnant_t2', 'pregnant_t3', 'nursing')),
    auth_user_id             uuid unique references auth.users(id) on delete cascade,
    created_at               timestamptz not null default now(),
    updated_at               timestamptz not null default now()
);

create index profiles_auth_user_id_idx on profiles (auth_user_id);

-- ── receipts ────────────────────────────────────────────────────────────
-- One row per upload. raw_text keeps the OCR/extracted text for debugging
-- and re-parsing; status flips to 'confirmed' when the review screen
-- finalizes the receipt and triggers matching. profile_id owns the receipt
-- (multi-user, migration 0007).
create table receipts (
    id            uuid primary key default gen_random_uuid(),
    profile_id    smallint not null default 1 references profiles(id),
    source        text not null check (source in ('image', 'pdf', 'pasted_text')),
    raw_text      text,
    store         text,
    purchased_at  date,
    status        text not null default 'pending' check (status in ('pending', 'confirmed')),
    created_at    timestamptz not null default now()
);

create index receipts_profile_id_idx on receipts (profile_id);

-- ── receipt_items ───────────────────────────────────────────────────────
-- Parsed line items + matched nutrition data, per 100g. Field names mirror
-- the resolver/matcher's MatchedProduct / NutritionValues shapes 1:1 so
-- that code can persist its output without translation. parsed_name
-- (migration 0014) snapshots the parser's cleaned name at insert time, so
-- later user edits to `name` don't move the verified-match learning key.
create table receipt_items (
    id                 uuid primary key default gen_random_uuid(),
    receipt_id         uuid not null references receipts(id) on delete cascade,

    -- parsed fields (receipt_text_parser.py)
    name               text not null,
    parsed_name        text,
    original_text      text,
    quantity           numeric,
    unit               text,
    price              numeric,
    category           text,
    is_non_food        boolean not null default false,
    uncertain          boolean not null default false,

    -- match metadata (MatchedProduct)
    match_type         text check (match_type in ('learned', 'exact', 'fuzzy', 'bls', 'fallback', 'none')),
    confidence         numeric check (confidence between 0 and 1),
    identity_conf      numeric check (identity_conf between 0 and 1),
    nutrition_conf     numeric check (nutrition_conf between 0 and 1),
    unknown            boolean not null default false,
    data_source        text,
    matched_name       text,
    brand              text,
    off_id             text,
    bls_code           text,
    fallback_category  text,

    -- nutrition values (NutritionValues, per 100g)
    protein_g          numeric,
    fat_g              numeric,
    carbs_g            numeric,
    saturated_fat_g    numeric,
    fiber_g            numeric,
    sugar_g            numeric,
    calories_kcal      numeric,
    processed_score    numeric,
    iron_mg            numeric,
    calcium_mg         numeric,
    micros             jsonb not null default '{}'::jsonb,
    sources            jsonb not null default '{}'::jsonb,

    created_at         timestamptz not null default now()
);

create index receipt_items_receipt_id_idx on receipt_items (receipt_id);

-- ── verified_matches ────────────────────────────────────────────────────
-- User-corrected matches, keyed by services/verified_matches.py's
-- normalize_match_key(). Global on purpose, not per-user: a shared
-- "we already figured this product out" cache, not personal data.
create table verified_matches (
    id            uuid primary key default gen_random_uuid(),
    match_key     text not null,
    store         text not null default '',
    matched_name  text,
    off_id        text,
    bls_code      text,
    nutrition     jsonb not null default '{}'::jsonb,
    updated_at    timestamptz not null default now(),
    unique (match_key, store)
);

-- ── non_food_terms ──────────────────────────────────────────────────────
-- Learned "not food" corrections, filtered out of future receipts at
-- upload time. Global, same reasoning as verified_matches above.
create table non_food_terms (
    id          uuid primary key default gen_random_uuid(),
    term_key    text not null unique,
    raw_text    text,
    created_at  timestamptz not null default now()
);

-- ── rejected_matches ────────────────────────────────────────────────────
-- The negative counterpart to verified_matches: a candidate a user
-- dismissed in the "Fix match" panel as not a real match, excluded from
-- future searches for the same normalized text on any future receipt.
create table rejected_matches (
    id          uuid primary key default gen_random_uuid(),
    match_key   text not null,
    source      text not null check (source in ('off', 'bls')),
    external_id text not null,
    created_at  timestamptz not null default now(),
    unique (match_key, source, external_id)
);

create index rejected_matches_match_key_idx on rejected_matches (match_key);

-- ── user_feedback ───────────────────────────────────────────────────────
-- One-time NPS satisfaction score, unrelated to any single recipe (see
-- recipes.feedback below for the per-recipe thumbs up/down instead).
create table user_feedback (
    id          uuid primary key default gen_random_uuid(),
    profile_id  smallint not null default 1 references profiles(id),
    nps_score   smallint not null check (nps_score between 1 and 10),
    created_at  timestamptz not null default now()
);

create index user_feedback_profile_id_idx on user_feedback (profile_id);

-- ── recipes ─────────────────────────────────────────────────────────────
-- Groq-generated recipes (services/recipe_engine.py). `ingredients` (jsonb)
-- stores [{name, quantity}] -- a natural-language amount per ingredient
-- (e.g. "200 g", "1 tbsp"), not a fixed schema. dietary_label is the
-- model's own classification of the recipe's ACTUAL ingredients (may
-- differ from the style that was requested); feedback is a per-recipe
-- thumbs up/down; archived_at is a soft-delete for the recipe list's "x".
create table recipes (
    id                             uuid primary key default gen_random_uuid(),
    profile_id                     smallint not null default 1 references profiles(id),
    title                          text not null,
    ingredients                    jsonb not null default '[]',
    steps                          text[] not null default '{}',
    prep_minutes                   smallint,
    cook_minutes                   smallint,
    servings                       smallint,
    calories_kcal                  numeric,
    protein_g                      numeric,
    fat_g                          numeric,
    carbs_g                        numeric,
    fiber_g                        numeric,
    has_low_confidence_ingredient  boolean not null default false,
    dietary_label                  text check (dietary_label in ('omnivore', 'pescatarian', 'vegetarian', 'vegan')),
    feedback                       text check (feedback in ('up', 'down')),
    archived_at                    timestamptz,
    created_at                     timestamptz not null default now()
);

create index recipes_profile_id_created_at_idx on recipes (profile_id, created_at desc);

-- ── pantry_removals ─────────────────────────────────────────────────────
-- The pantry ("what's currently in stock") is purchases MINUS withdrawals,
-- and withdrawals are an append-only LEDGER, never a status column on
-- receipt_items -- receipt_items stays an immutable purchase fact, so the
-- pantry can be derived at read time (v_pantry, below) without the
-- purchase/consumption analytics double-counting anything. 'eaten' counts
-- as consumption; 'removed' (spoiled/given away/miscan) does not -- both
-- empty the pantry, only later consumption-gap analysis tells them apart.
-- `quantity` NULL = the whole lot was withdrawn at once.
create table pantry_removals (
    id               uuid primary key default gen_random_uuid(),
    receipt_item_id  uuid not null references receipt_items(id) on delete cascade,
    reason           text not null check (reason in ('eaten', 'removed')),
    quantity         numeric,
    removed_at       timestamptz not null default now()
);

create index pantry_removals_item_idx on pantry_removals (receipt_item_id);

-- ── v_pantry (view) ─────────────────────────────────────────────────────
-- A lot is "in the pantry" once its receipt is confirmed, it's food, and
-- its purchased quantity minus every withdrawal against it is still > 0.
-- remaining_quantity supports partial withdrawals ("ate 0.2 l of 3 l");
-- a NULL receipt_items.quantity (no parsed amount) is treated as one unit,
-- matching the parser's own default. profile_id/store/purchased_at are
-- lifted from the parent receipt so the API can scope by owner and render
-- a row without a second join -- ownership is transitive through
-- receipts.profile_id, no redundant column here.
create view v_pantry as
select
    ri.*,
    r.profile_id   as profile_id,
    r.store        as store,
    r.purchased_at as purchased_at,
    coalesce(ri.quantity, 1) - coalesce((
        select sum(coalesce(pr.quantity, coalesce(ri.quantity, 1)))
        from pantry_removals pr
        where pr.receipt_item_id = ri.id
    ), 0) as remaining_quantity
from receipt_items ri
join receipts r on r.id = ri.receipt_id
where r.status = 'confirmed'
  and ri.is_non_food = false
  and coalesce(ri.quantity, 1) - coalesce((
        select sum(coalesce(pr.quantity, coalesce(ri.quantity, 1)))
        from pantry_removals pr
        where pr.receipt_item_id = ri.id
    ), 0) > 0;

-- Run the view with the CALLER's privileges, not the owner's, so RLS on
-- the underlying tables actually applies to whoever queries it (a view
-- defaults to executing as its owner, which would otherwise bypass RLS).
alter view v_pantry set (security_invoker = on);

-- ── pantry_shelf_life ───────────────────────────────────────────────────
-- Per-profile OVERRIDES of the estimated shelf life (in days) for a food
-- group (services/shelf_life.py's FOOD_GROUPS) -- a group with no row here
-- falls back to that module's DEFAULT_SHELF_LIFE, so a brand-new profile
-- needs no seed rows. shelf_life_days NULL = "no estimate" for that group.
create table pantry_shelf_life (
    profile_id       smallint not null references profiles(id) on delete cascade,
    food_group       text not null,
    shelf_life_days  integer check (shelf_life_days is null or shelf_life_days > 0),
    updated_at       timestamptz not null default now(),
    primary key (profile_id, food_group)
);

-- ── gap_recommendations ─────────────────────────────────────────────────
-- Insights page "Nährbert's Quick Wins" (Groq-generated). One row per
-- profile, replaced on regenerate -- NOT an accumulating history like
-- recipes. profile_id is the primary key itself so an upsert on it gives
-- "keep only the latest" for free. Regeneration itself is gated in the
-- application layer (once a day, only after a new receipt is confirmed),
-- not by anything in this table.
create table gap_recommendations (
    profile_id  smallint primary key references profiles(id) on delete cascade,
    summary     text not null,
    items       jsonb not null default '[]',
    created_at  timestamptz not null default now()
);

-- ── Row-level security ──────────────────────────────────────────────────
-- Enabled on every table, with NO policies -- see the file header for why
-- that's the deliberate final state, not a gap. (rejected_matches and
-- gap_recommendations didn't exist yet when this was first done on the
-- live project and were missed at the time; both are included here.)
alter table profiles          enable row level security;
alter table receipts          enable row level security;
alter table receipt_items     enable row level security;
alter table verified_matches  enable row level security;
alter table non_food_terms    enable row level security;
alter table rejected_matches  enable row level security;
alter table user_feedback     enable row level security;
alter table recipes           enable row level security;
alter table pantry_removals   enable row level security;
alter table pantry_shelf_life enable row level security;
alter table gap_recommendations enable row level security;
