-- naehrbert multi-user (simplistic) -- a login screen picks an existing
-- profile by name or creates a new one; no passwords yet, the frontend just
-- remembers the chosen profiles.id and sends it as an X-Profile-Id header
-- on every request ("we will implement a proper auth later" -- this is the
-- seam that later swaps a header for a real session/JWT).
--
-- profiles.id was pinned to 1 with a single_row check (Epic 0.1's
-- single-user assumption). Multi-user needs that check gone and the column
-- auto-generating fresh ids for new signups instead of always defaulting
-- to 1.

alter table profiles drop constraint single_row;
alter table profiles alter column id drop default;
alter table profiles alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('profiles', 'id'), (select max(id) from profiles));

-- receipts had no owner column at all (fine for one user; not for many).
-- Defaulted to 1 so every existing receipt is retroactively owned by the
-- original single-user profile row, no backfill script needed.
alter table receipts add column profile_id smallint not null default 1 references profiles(id);
create index receipts_profile_id_idx on receipts (profile_id);

-- verified_matches / non_food_terms stay global on purpose: they're a
-- shared "we already figured this product out" cache keyed on
-- (match_key, store), not personal data, so there's no reason to make
-- every new user re-teach the app the same corrections.
